server:
  port: 8889
spring:
  application:
    name: douyin-helper
  profiles:
    include: bhy
#douyin:
#  download:
#    local-path: 下载文件存放根路径
##### 使用 Charles、Fiddler 等抓包工具获取手机APP的http请求头、cookie信息
#    api:
#      tt-token: ""
#      tt-trace-id: ""
#      gorgon: ""
#      ss-dp: ""
#      user-agent: ""
#      cookies:
#        msh: ""
#        d_ticket: ""
#        sid_guard: ""
#        uid_tt: ""
#        sid_tt: ""
#        sessionid: ""
#        odin_tt: ""
#        install_id: ""
#        ttreq: ""